# Single-package workspace (pnpm v11 project settings).
strictPeerDependencies: false
autoInstallPeers: true
nodeLinker: hoisted
blockExoticSubdeps: false

overrides:
  "lockwright-lib-constants": "git+https://github.com/Dexterity-Works/lockwright-lib-constants.git#f6142c9554e9f972519dd8115b2b73f02b73d5fb"
  "lockwright-lib-ui-react-native-components": "git+https://github.com/Dexterity-Works/lockwright-lib-ui-react-native-components.git#design-system-v2"

allowBuilds:
  "@electron/node-gyp@https://codeload.github.com/electron/node-gyp/tar.gz/06b29aafb7708acef8b3669835c8a7857ebc92d2": true
  "lockwright-lib-ui-react-native-components@https://codeload.github.com/Dexterity-Works/lockwright-lib-ui-react-native-components/tar.gz/82167746355a4d1b931dae2c3d4abe10a7e10b7e": true
  "@tetherto/tether-dev-docs@https://codeload.github.com/Dexterity-Works/tether-dev-docs/tar.gz/cb82786f04714a56577df1555db947969ec90aeb": true
  "lockwright-lib-vault-core@file:../pearpass-lib-vault-core": true
  "lockwright-lib-vault@file:../pearpass-lib-vault": true
  "@tetherto/pearpass-lib-native-messaging-bridge@https://codeload.github.com/Dexterity-Works/pearpass-lib-native-messaging-bridge/tar.gz/8ad5022e06d1be141db20ac20e1fc57549859541": true
  "electron-winstaller@5.4.0": true
  "electron@33.4.11": true
  "esbuild@0.21.5": true
  "esbuild@0.24.2": true
